#eureka:
#  client:
#    service-url:
#      { defaultZone : "http://localhost:8010/eureka/"}

#primary
---
server:
  port: 8015      
spring:
  profiles: primary
words:  boat,book,vote,seat,backpack,partition,groundhog

#secondary
---
server:
  port: 8016
spring:
  profiles: secondary
words:  icicle,refrigerator,blizzard,snowball

        