---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: user1
    password: passwd123   
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/tulasidamarla/config-properties
          #use the below two properties for private access
          #username: tulasidamarla 
          #password: krishna@418
          
          #search for subfolders name starts with station
          search-paths:
            - 'station*'
          repos:
            #alternate repo name 'perf'
            perf:
              #url pattern For ex: localhost:8888/s1rates/perf
              pattern:
                -"*/perf"
              uri: https://github.com/tulasidamarla/config-properties-perf
              search-paths:
                -'station*'      